"""added created on field to notes

Revision ID: 1d806e0d59ad
Revises: 4c9077858c3c
Create Date: 2016-06-04 01:46:42.529921

"""

# revision identifiers, used by Alembic.
revision = '1d806e0d59ad'
down_revision = '4c9077858c3c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_notes', sa.Column('created_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_notes', 'created_on')
    ### end Alembic commands ###
