"""added feedback_id to GradeResponse table

Revision ID: 20f787d6d8d4
Revises: d347dd2d8851
Create Date: 2016-04-28 14:19:48.320720

"""

# revision identifiers, used by Alembic.
revision = '20f787d6d8d4'
down_revision = 'd347dd2d8851'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_grade', sa.Column('feedback_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_grade', 'feedback_id')
    ### end Alembic commands ###
