"""added notes table and user grading sessions

Revision ID: 452aa75feb90
Revises: 65dec3b9f282
Create Date: 2016-05-28 14:14:55.373328

"""

# revision identifiers, used by Alembic.
revision = '452aa75feb90'
down_revision = '65dec3b9f282'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exercise_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_grading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_on', sa.DateTime(), nullable=True),
    sa.Column('ended_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'response_grade', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column(u'response_grade', sa.Column('submitted_on', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'response_grade', 'user_grading_sessions', ['session_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response_grade', type_='foreignkey')
    op.drop_column(u'response_grade', 'submitted_on')
    op.drop_column(u'response_grade', 'session_id')
    op.drop_table('user_grading_sessions')
    op.drop_table('user_exercise_notes')
    ### end Alembic commands ###
