"""added started_on field to ResponseGrade

Revision ID: 50a9074e5d50
Revises: 00032b55963b
Create Date: 2016-11-29 15:46:07.003274

"""

# revision identifiers, used by Alembic.
revision = '50a9074e5d50'
down_revision = '00032b55963b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_grade', sa.Column('started_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_grade', 'started_on')
    ### end Alembic commands ###
