"""added feature and forest columns to Exercise table

Revision ID: 65dec3b9f282
Revises: 20f787d6d8d4
Create Date: 2016-05-09 08:39:57.764346

"""

# revision identifiers, used by Alembic.
revision = '65dec3b9f282'
down_revision = '20f787d6d8d4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('features', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('exercises', sa.Column('forest_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'forest_name')
    op.drop_column('exercises', 'features')
    ### end Alembic commands ###
