"""added step_id column to response model

Revision ID: 8416c2233a9e
Revises: 21bb97866ed8
Create Date: 2016-06-17 16:59:07.605225

"""

# revision identifiers, used by Alembic.
revision = '8416c2233a9e'
down_revision = '21bb97866ed8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('step_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'responses', ['step_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='unique')
    op.drop_column('responses', 'step_id')
    ### end Alembic commands ###
