"""added subject column to responses and exercises

Revision ID: a7fae591baaf
Revises: 452aa75feb90
Create Date: 2016-06-02 16:07:10.768466

"""

# revision identifiers, used by Alembic.
revision = 'a7fae591baaf'
down_revision = '452aa75feb90'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

subject_table = sa.table('subjects',
                         sa.column('id', sa.Integer),
                         sa.column('name', sa.String),
                         sa.column('tag', sa.String))

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_unqualified_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'exercises', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key('exercises_subject_id_fkey', 'exercises', 'subjects', ['subject_id'], ['id'])
    op.add_column(u'responses', sa.Column('subject', sa.String(), nullable=True))
    op.add_column(u'responses', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key('responses_subject_id_fkey', 'responses', 'subjects', ['subject_id'], ['id'])
    ### end Alembic commands ###
    op.bulk_insert(subject_table,
                   [
                       {'id': 1, 'name': 'Biology', 'tag': 'apbio'},
                       {'id': 2, 'name': 'Physics', 'tag': 'k12phys'}
                   ]
                   )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('responses_subject_id_fkey', 'responses', type_='foreignkey')
    op.drop_column(u'responses', 'subject_id')
    op.drop_column(u'responses', 'subject')
    op.drop_constraint('exercises_subject_id_fkey', 'exercises', type_='foreignkey')
    op.drop_column(u'exercises', 'subject_id')
    op.drop_table('user_unqualified_exercises')
    op.drop_table('subjects')
    ### end Alembic commands ###
