"""added created_on and updated_on columns to responses and exercises tables

Revision ID: cd8b85614a25
Revises: fa43b02e45fa
Create Date: 2017-02-03 11:21:43.103895

"""

# revision identifiers, used by Alembic.
revision = 'cd8b85614a25'
down_revision = 'fa43b02e45fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('exercises', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('responses', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('responses', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'updated_on')
    op.drop_column('responses', 'created_on')
    op.drop_column('exercises', 'updated_on')
    op.drop_column('exercises', 'created_on')
    # ### end Alembic commands ###
